"""Auto-generated by test_utils.write_generated_test - do not hand-edit.

Each test function below replays one scorecard's recorded call_sequence from
closure_test_scorecards.json, in order, exactly as the real do_closure (or its
hand-orchestrated equivalent - see each function's own docstring) executed it
for that test. Regenerate one test with
write_generated_test(test_id, display=...); it replaces only that test's own
BEGIN/END block below, leaving every other already-generated test untouched.
"""
import numpy as np

from map_of_squares import StateEnum, InvalidTilingError
from representation import build_map_of_squares, display_closure_step, RealSpaceMargin
from closure import (find_alerts_set_links, find_secondary_links, assign_paths,
                      get_blocked_links, set_blocked_links, place_square_in_seat_closed,
                      clear_all_but_state, check_tiling_invariant,
                      seed_blocked_paths, apply_blocked_paths, propagate_blocked_tmp_closed)


# === BEGIN GENERATED TEST: test_line ===
def test_line_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_line').

    Six squares placed so their blocked diagonal neighbours pair into three mutual alert-blocking quadrants, chained by a plain diagonal link from (9,1). Unbranched, so get_blocked_links is empty in the original stage-by-stage test.
    """
    m = build_map_of_squares(11, 10)
    for pos in [[2, 5], [4, 3], [5, 8], [6, 1], [7, 6], [9, 4]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[1, 4], [1, 6], [3, 2], [3, 4], [3, 6], [4, 7], [4, 9], [5, 0], [5, 2], [5, 4], [6, 5], [6, 7], [6, 9], [7, 0], [7, 2], [8, 3], [8, 5], [8, 7], [10, 3], [10, 5]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    # ASSERT: m[9,1].forces == {(7,3)} (chain start, not itself alert_blocked)
    # ASSERT: m[7,3], m[5,5], m[3,7] are each .alert_blocked
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    # ASSERT: get_blocked_links(m) == set() (no self-contradicting path)
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_line', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Position is approximate: the ORIGINAL source test displays here after only find_alerts_set_links + assign_paths + get_blocked_links (3 calls) - it never calls find_secondary_links (this scorecard's step 2) before this display. This scorecard's call_sequence is a full do_closure reconstruction run separately on the same initial board, for parity with the other scorecards. Title: 'line (simple chain): alert_blocked=blue, alert_chosen=yellow, both=green'.
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    # Hand-edited, diverges from write_generated_test's default rendering of
    # this call_sequence step: exercises the new, separate blocked_paths
    # mechanism (closure.seed_blocked_paths/apply_blocked_paths/
    # propagate_blocked_tmp_closed) in place of get_blocked_links/
    # set_blocked_links for this one round. Not do_closure's own pipeline -
    # do_closure still calls get_blocked_links/set_blocked_links unchanged.
    # Regenerating this test (write_generated_test('test_line', ...)) will
    # overwrite this block back to the default rendering.
    seed_blocked_paths(m)
    apply_blocked_paths(m)
    propagate_blocked_tmp_closed(m)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
# === END GENERATED TEST: test_line ===


# === BEGIN GENERATED TEST: test_show_other_full_2x2 ===
def test_show_other_full_2x2_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_show_other_full_2x2').

    Four squares placed so that closure's own placement decisions (not the hand-chosen squares directly) complete a fully-blocked 2x2 block somewhere on the board. check_tiling_invariant, run once at the very end of do_closure, catches this and raises - the whole call sequence up to and including the final check_tiling_invariant step still ran; the raise happens on that last step, not earlier.
    """
    m = build_map_of_squares(9, 9)
    for pos in [[3, 3], [4, 3], [5, 6], [6, 6]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[2, 2], [2, 4], [3, 2], [3, 4], [4, 2], [4, 4], [4, 5], [4, 7], [5, 2], [5, 4], [5, 5], [5, 7], [6, 5], [6, 7], [7, 5], [7, 7]]:
        m[tuple(pos)].state = StateEnum.blocked

    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_show_other_full_2x2', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Title: 'initial state' - shows the four hand-placed squares before do_closure runs at all (position 0 = before any call_sequence step).
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    try:
        check_tiling_invariant(m)
        raise AssertionError('check_tiling_invariant' + ' was expected to raise InvalidTilingError but did not')
    except InvalidTilingError as e:
        pass  # expected - see raised_message in the scorecard
    # ASSERT: do_closure raises InvalidTilingError
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_show_other_full_2x2', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Runs even though step 14 (check_tiling_invariant) raised - the test's try/except catches InvalidTilingError and displays the resulting (invalid) board, with the error folded into the title.
# === END GENERATED TEST: test_show_other_full_2x2 ===


# === BEGIN GENERATED TEST: test_margin_free_4x4realmap ===
def test_margin_free_4x4realmap_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_margin_free_4x4realmap').

    n=3: a 4x4 free core wrapped in a blocked margin. The source test repeatedly picks a random still-free cell, chases its forced_closure, resets bookkeeping, and re-runs do_closure(show=True) until is_realmap_cover_complete says the real-space map has no gap left (source test does not seed random.choice, so its exact placement order varies run to run; this scorecard fixes random.seed(7) so the recorded call sequence is reproducible). initial_map here is the board state immediately before the FINAL do_closure call. Empirically (checked across dozens of seeds, both n=3 and n=5 cores), coverage always flips to complete at the manual forced_closure placement itself, one step before do_closure even runs - every field in this scorecard's map_changed_flags is false because the board is already at a local fixed point (no new alerts, no contradictions, no seats) by the time do_closure starts. do_closure's role in this final round is pure post-hoc validation - contradiction check plus check_tiling_invariant - not placement. That's a real, load-bearing fact about this pipeline, not an artifact of this particular seed.
    """
    m = build_map_of_squares(7, 7)
    for pos in [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [2, 0], [2, 2], [2, 4], [2, 6], [3, 0], [3, 4], [3, 6], [4, 0], [4, 2], [4, 4], [4, 6], [6, 0], [6, 1], [6, 2], [6, 3], [6, 4], [6, 5], [6, 6]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [1, 6], [2, 1], [2, 3], [2, 5], [3, 1], [3, 3], [3, 5], [4, 1], [4, 3], [4, 5], [5, 0], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5], [5, 6]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_margin_free_4x4realmap', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=RealSpaceMargin(width=2, crop=False), roi_margin=1)
    # display note: do_closure's own internal display (do_closure(..., show=True, margin=MARGIN, roi_margin=ROI_MARGIN)) for this final round - already appears as the step-7 'display_closure_step' entry in call_sequence; this item adds its flags.
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
    # ASSERT: is_realmap_cover_complete(m, margin=2) is True
# === END GENERATED TEST: test_margin_free_4x4realmap ===


# === BEGIN GENERATED TEST: test_get_and_set_blocked_links_marks_blocked_tmp ===
def test_get_and_set_blocked_links_marks_blocked_tmp_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_get_and_set_blocked_links_marks_blocked_tmp').

    Border-wrapped 12x12 board with two hand-placed dominoes. Not a full do_closure call: only one round, and find_secondary_links is skipped entirely (this test predates/bypasses it), so the 5-step sequence here is a strict subsequence of do_closure's own. get_blocked_links finds six self-contradicting path ids ({26,33,62,64,90,117}); set_blocked_links blocks their six origin cells outright. Five of the six are later locally confirmed by a seat place_square_in_seat_closed fills next to them - (5,2) is the exception, with no bordering seat, invisible to any purely local read of the resulting board. This is the concrete case do_closure's own docstring cites for why get_blocked_links/set_blocked_links has to run before place_square_in_seat_closed at all.
    """
    m = build_map_of_squares(12, 12)
    for pos in [[4, 7], [5, 7], [8, 3], [8, 4]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [0, 10], [0, 11], [1, 0], [1, 11], [2, 0], [2, 11], [3, 0], [3, 6], [3, 8], [3, 11], [4, 0], [4, 6], [4, 8], [4, 11], [5, 0], [5, 6], [5, 8], [5, 11], [6, 0], [6, 6], [6, 8], [6, 11], [7, 0], [7, 2], [7, 3], [7, 4], [7, 5], [7, 11], [8, 0], [8, 11], [9, 0], [9, 2], [9, 3], [9, 4], [9, 5], [9, 11], [10, 0], [10, 11], [11, 0], [11, 1], [11, 2], [11, 3], [11, 4], [11, 5], [11, 6], [11, 7], [11, 8], [11, 9], [11, 10], [11, 11]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    # ASSERT: get_blocked_links(m) == {26, 33, 62, 64, 90, 117}
    set_blocked_links(m, p)
    # ASSERT: blocked_tmp cells == {(2,2),(2,9),(5,2),(5,4),(7,6),(9,9)}, each .state==blocked, .forces==.forced_by==set()
    # ASSERT: no cell's path_id retains any id in p; no cell's forces/forced_by retains any blocked_tmp position
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_get_and_set_blocked_links_marks_blocked_tmp', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Falls between this scorecard's step 4 (set_blocked_links) and step 5 (place_square_in_seat_closed) - blocked_tmp cells show in red. Title: 'get_blocked_links/set_blocked_links: blocked_tmp in red'. A further do_closure(show=True) call follows (after clear_all_but_state), with its own separate internal display - not represented in this scorecard's 5-step call_sequence.
    place_square_in_seat_closed(m)
    # ASSERT: new seats fill 4 of the 6 corroborating positions; (5,2) has no bordering new seat
# === END GENERATED TEST: test_get_and_set_blocked_links_marks_blocked_tmp ===


# === BEGIN GENERATED TEST: test_rectangle ===
def test_rectangle_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_rectangle').

    Smallest input that gets a seat started: two vertically-stacked blocked cells at (2,3)/(3,3), nothing else. Each threatens the seat forming immediately to its own side.
    """
    m = build_map_of_squares(7, 7)
    for pos in [[2, 3], [3, 3]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
    # ASSERT: check_tiling_invariant(m) does not raise
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_rectangle', show_links=True, show_real=False, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Called after do_closure completes and after the test's own redundant check_tiling_invariant(m) re-check (not itself a call_sequence entry). Title: '4: check_tiling_invariant (invariant held - no state change)'.
# === END GENERATED TEST: test_rectangle ===


# === BEGIN GENERATED TEST: test_tree_fan_out ===
def test_tree_fan_out_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_tree_fan_out').

    Four squares each alert-block one diagonal neighbour of the shared centre (4,4) via a separate corner, so (4,4) ends up forcing all four despite never being alert_chosen itself - .forces and .alert_chosen are independent facts.
    """
    m = build_map_of_squares(10, 10)
    for pos in [[1, 4], [4, 1], [4, 7], [7, 4]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[0, 3], [0, 5], [2, 3], [2, 5], [3, 0], [3, 2], [3, 6], [3, 8], [5, 0], [5, 2], [5, 6], [5, 8], [6, 3], [6, 5], [8, 3], [8, 5]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
    # ASSERT: not m[4,4].alert_chosen and m[4,4].forced_by == set()
    # ASSERT: m[4,4].forces == {(2,2),(2,6),(6,2),(6,6)}
    # ASSERT: each of (2,2),(2,6),(6,2),(6,6) is alert_chosen with (4,4) in forced_by
    # ASSERT: get_blocked_links(m) == set()
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_tree_fan_out', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Called after the full call_sequence completes and after a redundant get_blocked_links(m) re-check (not itself a call_sequence entry). Title: 'tree (fan-out)'.
# === END GENERATED TEST: test_tree_fan_out ===


# === BEGIN GENERATED TEST: test_tree_fan_in ===
def test_tree_fan_in_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_tree_fan_in').

    (3,3) is forced_by four separate items at once - (2,1),(4,1),(4,3),(4,5) - none needing any of the others. Either of two different later placements (6,4) or (2,1)) reaches it via forced_closure, confirming it's a real fan-in, not just one link in a chain.
    """
    m = build_map_of_squares(10, 10)
    for pos in [[1, 3], [1, 4], [5, 7], [6, 7], [7, 7], [8, 7]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[0, 2], [0, 3], [0, 4], [0, 5], [2, 2], [2, 3], [2, 4], [2, 5], [4, 6], [4, 8], [5, 6], [5, 8], [6, 6], [6, 8], [7, 6], [7, 8], [8, 6], [8, 8], [9, 6], [9, 8]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
    # ASSERT: m[3,3].alert_chosen and not m[3,3].forces
    # ASSERT: {(2,1),(4,1),(4,3),(4,5)} <= m[3,3].forced_by
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_tree_fan_in', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Title: 'line into cycle' - the display tied to this scorecard's own recorded call_sequence (the first of the source test's three do_closure/display rounds).
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_tree_fan_in', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Title: 'fan-in forced via (6, 4)' - occurs after an additional place_squares(forced_closure(m, (6, 4))) call made directly by the test, outside do_closure and not represented in call_sequence. A third display ('fan-in forced via (2, 1)') exists in the source test but belongs to a second, independent do_closure call on a fresh copy of the same initial grid - out of scope for this scorecard's single call_sequence, so omitted here.
# === END GENERATED TEST: test_tree_fan_in ===


# === BEGIN GENERATED TEST: test_line_into_eye ===
def test_line_into_eye_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_line_into_eye').

    (1,4) is a pure diagonal linker into (1,6): it has real .forces without being alert_chosen itself. (1,6) and (1,8) are a genuine mutual pair - each is alert_chosen and forces the other - a real bidirectional link. Placing (1,4) afterwards (outside do_closure, via forced_closure+place_squares) drags both bidirectionally-linked cells chosen too.
    """
    m = build_map_of_squares(10, 10)
    for pos in [[0, 6], [3, 7]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[1, 5], [1, 7], [2, 6], [2, 8], [4, 6], [4, 8]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
    # ASSERT: not m[1,4].alert_chosen; m[1,6].alert_chosen; m[1,8].alert_chosen
    # ASSERT: m[1,4].forces == {(1,6)}; m[1,6].forces == {(1,8)}; (1,6) in m[1,8].forced_by
    # ASSERT: m[1,4].path_id == set() (single-target entry pruned by assign_paths)
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_line_into_eye', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Title: 'line into cycle: before placing (1, 4)'.
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_line_into_eye', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Title: 'line into cycle: after placing (1, 4)' - occurs after an additional place_squares(forced_closure(m, (1, 4))) call, outside do_closure and not represented in call_sequence.
# === END GENERATED TEST: test_line_into_eye ===


# === BEGIN GENERATED TEST: test_eye_outwards ===
def test_eye_outwards_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_eye_outwards').

    A bidirectional link with a line feeding outwards from it in the opposite direction from test_line_into_eye - display-only in the source test, no assertions there, so this scorecard's asserts are left empty; useful as a pure structural example.
    """
    m = build_map_of_squares(10, 10)
    for pos in [[1, 5], [1, 7], [4, 2], [4, 6]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[0, 4], [0, 6], [0, 8], [2, 4], [2, 6], [2, 8], [3, 1], [3, 3], [3, 5], [3, 7], [5, 1], [5, 3], [5, 5], [5, 7]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_eye_outwards', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Title: 'cycle line outwards: before placing (1, 2)'.
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_eye_outwards', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Title: 'cycle line outwards: after placing (1, 2)' - occurs after an additional place_squares(forced_closure(m, (1, 2))) call, outside do_closure and not represented in call_sequence.
# === END GENERATED TEST: test_eye_outwards ===


# === BEGIN GENERATED TEST: test_seat_from_two_alert_blocked ===
def test_seat_from_two_alert_blocked_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_seat_from_two_alert_blocked').

    Regression case for find_secondary_links. Without it, (7,5) used to end up chosen with an empty .forced_by - discovered only by place_square_in_seat_closed's raw state scan, invisible to the alert/path bookkeeping. find_secondary_links simulates (5,4) and (7,3) both chosen together (combining candidate a=(5,4) with P=(6,3)'s promised corner B=(7,3)) and finds this jointly completes a fresh seat at (7,5) - so (5,4) gets linked to it directly, and forced_closure(m,(5,4)) now reaches (7,5) too.
    """
    m = build_map_of_squares(12, 12)
    for pos in [[5, 1], [8, 3]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[4, 0], [4, 2], [6, 0], [6, 2], [7, 2], [7, 4], [9, 2], [9, 4]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_seat_from_two_alert_blocked', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: This is do_closure's own internal display (do_closure(m, 'initial', show=True)) - it already appears as the step-7 'display_closure_step' entry in call_sequence; this item adds the flags that entry doesn't carry. A further place_and_chase(...) round follows, with its own separate do_closure(show=False) call plus an external display_closure_step call - not represented here.
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
    # ASSERT: m[7,5].forced_by == {(5,4)}
    # ASSERT: forced_closure(m, (5,4)) == {(5,4),(7,3),(7,5)}
# === END GENERATED TEST: test_seat_from_two_alert_blocked ===


# === BEGIN GENERATED TEST: test_frozen_area ===
def test_frozen_area_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_frozen_area').

    Same phenomenon as test_seat_from_two_alert_blocked, one round later: by the end of round 2, find_secondary_links has already linked both (6,7) and (6,8) - the two cells round 3 is about to place - directly to (8,7), so forced_closure(m,(6,7)) reaches it too, instead of leaving it for place_square_in_seat_closed's raw scan to discover once round 3's placement happens to complete its seat. Initial map here is the board state after rounds 1-2 (placing (4,4) then (5,4) and chasing each), immediately before round 3 places (6,7) and its forced_closure and this scorecard's do_closure call runs.
    """
    m = build_map_of_squares(11, 11)
    for pos in [[1, 1], [1, 9], [4, 4], [5, 4], [9, 1], [9, 9]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [0, 10], [1, 0], [1, 10], [2, 0], [2, 2], [2, 8], [2, 10], [3, 0], [3, 3], [3, 5], [3, 10], [4, 0], [4, 3], [4, 5], [4, 10], [5, 0], [5, 3], [5, 5], [5, 10], [6, 0], [6, 3], [6, 5], [6, 10], [7, 0], [7, 10], [8, 0], [8, 2], [8, 8], [8, 10], [9, 0], [9, 10], [10, 0], [10, 1], [10, 2], [10, 3], [10, 4], [10, 5], [10, 6], [10, 7], [10, 8], [10, 9], [10, 10]]:
        m[tuple(pos)].state = StateEnum.blocked

    # ASSERT: m[8,7].forced_by == {(6,7),(6,8)} (evaluated before this call sequence, on the round-2 board)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    check_tiling_invariant(m)
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_frozen_area', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=None, roi_margin=0)
    # display note: Called by place_and_chase directly, after its own internal do_closure(show=False) call (matching this scorecard's own do_closure_sequence(show=False)) - not via do_closure's own show=True branch.
# === END GENERATED TEST: test_frozen_area ===


# === BEGIN GENERATED TEST: test_margin_free_3x3realmap ===
def test_margin_free_3x3realmap_generated():
    """Reconstructed from closure_test_scorecards.json (test_id='test_margin_free_3x3realmap').

    n=2: a 3x3 free core (odd interior) wrapped in build_margin_free_map's blocked ring. do_closure's own initial closure pass raises InvalidTilingError before any square is ever placed by the caller - too small a free core cannot be validly tiled at all.
    """
    m = build_map_of_squares(6, 6)
    for pos in [[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [2, 0], [2, 5], [3, 0], [3, 5], [5, 0], [5, 1], [5, 2], [5, 3], [5, 4], [5, 5]]:
        m[tuple(pos)].state = StateEnum.chosen
    for pos in [[1, 0], [1, 1], [1, 2], [1, 3], [1, 4], [1, 5], [2, 1], [2, 4], [3, 1], [3, 4], [4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5]]:
        m[tuple(pos)].state = StateEnum.blocked

    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    clear_all_but_state(m)
    find_alerts_set_links(m)
    find_secondary_links(m)
    assign_paths(m)
    p = get_blocked_links(m)
    set_blocked_links(m, p)
    place_square_in_seat_closed(m)
    try:
        check_tiling_invariant(m)
        raise AssertionError('check_tiling_invariant' + ' was expected to raise InvalidTilingError but did not')
    except InvalidTilingError as e:
        pass  # expected - see raised_message in the scorecard
    # ASSERT: do_closure raises InvalidTilingError on its first call
    colormap = np.zeros((*m.shape, 3))
    display_closure_step(m, 'test_margin_free_3x3realmap', show_links=True, show_real=True, show_entries_terminals=False, colormap=colormap, margin=RealSpaceMargin(width=2, crop=False), roi_margin=1)
    # display note: Only reached because do_closure raised InvalidTilingError at step 14 - the test's except block displays the rejected board, using the module-level MARGIN=RealSpaceMargin(width=2) and ROI_MARGIN=1.
# === END GENERATED TEST: test_margin_free_3x3realmap ===
