import json
import os
import re

import numpy as np

from representation import display_closure_step
from closure import do_closure, clear_all_but_state, forced_closure, place_squares

def place_and_chase(m, pos, title, show=True, show_entries_terminals=False):
    forced = forced_closure(m, pos)
    place_squares(m, list(forced))
    clear_all_but_state(m)
    do_closure(m, title, show=False)
    if show:
        colormap = np.zeros((*m.shape, 3))
        display_closure_step(m, title, show_links=True, show_real=True, colormap=colormap,
                              show_entries_terminals=show_entries_terminals)


_GENERATED_TEST_HEADER = '''"""Auto-generated by test_utils.write_generated_test - do not hand-edit.

Each test function below replays one scorecard's recorded call_sequence from
closure_test_scorecards.json, in order, exactly as the real do_closure (or its
hand-orchestrated equivalent - see each function's own docstring) executed it
for that test. Regenerate one test with
write_generated_test(test_id, display=...); it replaces only that test's own
BEGIN/END block below, leaving every other already-generated test untouched.
"""
import numpy as np

from map_of_squares import StateEnum, InvalidTilingError
from representation import build_map_of_squares, display_closure_step, RealSpaceMargin
from closure import (find_alerts_set_links, find_secondary_links, assign_paths,
                      get_blocked_links, set_blocked_links, place_square_in_seat_closed,
                      clear_all_but_state, check_tiling_invariant)
'''


def _render_margin(margin):
    if margin is None:
        return "None"
    return f"RealSpaceMargin(width={margin['width']}, crop={margin['crop']})"


def _render_test_body(test_id, sc, display):
    """Turns one closure_test_scorecards.json test entry into the indented
    body of a pytest function: map construction, then call_sequence replayed
    step by step (asserts as comments - their text is prose, not safe to
    exec), with each recorded display_closure_step call interleaved at its
    own position when display=True, omitted entirely when display=False.
    """
    indent = "    "
    lines = []

    lines.append(f'{indent}"""Reconstructed from closure_test_scorecards.json '
                 f'(test_id={test_id!r}).\n')
    lines.append(f"{indent}{sc['free_text']}")
    lines.append(f'{indent}"""')

    lines.append(f"{indent}m = build_map_of_squares({sc['initial_map_rows']}, "
                 f"{sc['initial_map_cols']})")
    if sc["initial_chosen_cells"]:
        lines.append(f"{indent}for pos in {sc['initial_chosen_cells']!r}:")
        lines.append(f"{indent}    m[tuple(pos)].state = StateEnum.chosen")
    if sc["initial_blocked_cells"]:
        lines.append(f"{indent}for pos in {sc['initial_blocked_cells']!r}:")
        lines.append(f"{indent}    m[tuple(pos)].state = StateEnum.blocked")
    lines.append("")

    displays_by_position = {}
    for d in sc["displays"]:
        displays_by_position.setdefault(d["position"], []).append(d)

    def emit_asserts(step_num):
        for a in sc["asserts"]:
            if a["evaluated_at_step"] == step_num:
                note = f" ({a['note']})" if a.get("note") else ""
                lines.append(f"{indent}# ASSERT: {a['assertion']}{note}")

    def emit_displays(position):
        if not display:
            return
        for d in displays_by_position.get(position, []):
            f = d["flags"]
            lines.append(f"{indent}colormap = np.zeros((*m.shape, 3))")
            lines.append(
                f"{indent}display_closure_step(m, {test_id!r}, "
                f"show_links={f['show_links']}, show_real={f['show_real']}, "
                f"show_entries_terminals={f['show_entries_terminals']}, "
                f"colormap=colormap, margin={_render_margin(f['margin'])}, "
                f"roi_margin={f['roi_margin']})"
            )
            if d.get("note"):
                lines.append(f"{indent}# display note: {d['note']}")

    emit_displays(0)   # position 0 = before any call_sequence step ran
    emit_asserts(0)

    for step in sc["call_sequence"]:
        fn = step["function_name"]
        n = step["step"]

        call = None
        if fn == "get_blocked_links":
            call = "p = get_blocked_links(m)"
        elif fn == "set_blocked_links":
            call = "set_blocked_links(m, p)"
        elif fn == "display_closure_step":
            call = None  # regenerated via emit_displays(n) below, respecting `display`
        else:
            call = f"{fn}(m)"

        if call is not None:
            if step.get("raised"):
                lines.append(f"{indent}try:")
                lines.append(f"{indent}    {call}")
                lines.append(f"{indent}    raise AssertionError("
                             f"{fn!r} + ' was expected to raise InvalidTilingError but did not')")
                lines.append(f"{indent}except InvalidTilingError as e:")
                lines.append(f"{indent}    pass  # expected - see raised_message in the scorecard")
            else:
                lines.append(f"{indent}{call}")

        emit_asserts(n)
        emit_displays(n)

    return "\n".join(lines) + "\n"


def _block_markers(test_id):
    return (f"# === BEGIN GENERATED TEST: {test_id} ===",
            f"# === END GENERATED TEST: {test_id} ===")


def write_generated_test(test_name, display, json_path=None, output_path=None):
    """Look up test_name in closure_test_scorecards.json and (re)write a
    pytest function that replays its recorded call_sequence into
    tests_generated.py - including every recorded display_closure_step call
    (with its recorded flags) when display=True, calling only the plain
    call_sequence functions (no display) when display=False.

    Regenerating the same test_name overwrites just that one function's own
    BEGIN/END-marked block in tests_generated.py, leaving every other
    previously-generated test in the file untouched. Returns output_path.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    json_path = json_path or os.path.join(here, "closure_test_scorecards.json")
    output_path = output_path or os.path.join(here, "tests_generated.py")

    with open(json_path) as f:
        db = json.load(f)

    tests = db["tests"]
    if test_name not in tests:
        raise KeyError(f"{test_name!r} not found in {json_path} - "
                        f"available test_ids: {sorted(tests)}")

    sc = tests[test_name]
    func_name = f"{test_name}_generated"
    body = _render_test_body(test_name, sc, display)

    begin, end = _block_markers(test_name)
    block = f"{begin}\ndef {func_name}():\n{body}{end}\n"

    if os.path.exists(output_path):
        with open(output_path) as f:
            content = f.read()
    else:
        content = _GENERATED_TEST_HEADER

    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if pattern.search(content):
        content = pattern.sub(block.rstrip("\n"), content)
    else:
        if not content.endswith("\n\n"):
            content = content.rstrip("\n") + "\n\n\n"
        content += block

    with open(output_path, "w") as f:
        f.write(content)

    return output_path